### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by phhoef** [Alfresco/alfresco-client-sdk#4]
Hi,

I came up with library after searching for any Java lib utilizing the Alfresco REST API.
Unfortunately the library seems to be not activiley devloped.
The Maven dependency is gone ...

@gavincornwell could you please give me a status update?
Should I use the library in projects?

Thanks

**Comment by gavincornwell** [comment]
Hi,

You’re correct this library is not being actively developed. This was a side project of an employee that is unfortunately no longer working for Alfresco.

You can use it in its current form but there will be no more development or bug fixes.

Incidentally, we’re currently evaluating internally how we can flag those projects that are not supported.

Hope that helps.
